
    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table address_owner (
        address_id bigint not null,
        owner_id bigint not null,
        primary key (address_id, owner_id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        id bigint generated by default as identity,
        owning_bank bigint not null,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null,
        primary key (creditcard_id, customer_id)
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists address_owner 
       add constraint FK6qqrocb197cfxf5of7wc9cu5s 
       foreign key (owner_id) 
       references Customer;

    alter table if exists address_owner 
       add constraint FKtlveceg81q5bjp3h05wef8s8h 
       foreign key (address_id) 
       references Address;

    alter table if exists CreditCard 
       add constraint FKl2cxkcslw7r5abrhbtj0qjyqo 
       foreign key (owning_bank) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table address_owner (
        address_id bigint not null,
        owner_id bigint not null,
        primary key (address_id, owner_id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        id bigint generated by default as identity,
        owning_bank bigint not null,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null,
        primary key (creditcard_id, customer_id)
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists address_owner 
       add constraint FK6qqrocb197cfxf5of7wc9cu5s 
       foreign key (owner_id) 
       references Customer;

    alter table if exists address_owner 
       add constraint FKtlveceg81q5bjp3h05wef8s8h 
       foreign key (address_id) 
       references Address;

    alter table if exists CreditCard 
       add constraint FKl2cxkcslw7r5abrhbtj0qjyqo 
       foreign key (owning_bank) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table address_owner (
        address_id bigint not null,
        owner_id bigint not null,
        primary key (address_id, owner_id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        id bigint generated by default as identity,
        owning_bank bigint not null,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null,
        primary key (creditcard_id, customer_id)
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists address_owner 
       add constraint FK6qqrocb197cfxf5of7wc9cu5s 
       foreign key (owner_id) 
       references Customer;

    alter table if exists address_owner 
       add constraint FKtlveceg81q5bjp3h05wef8s8h 
       foreign key (address_id) 
       references Address;

    alter table if exists CreditCard 
       add constraint FKl2cxkcslw7r5abrhbtj0qjyqo 
       foreign key (owning_bank) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table address_owner (
        address_id bigint not null,
        owner_id bigint not null,
        primary key (address_id, owner_id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        id bigint generated by default as identity,
        owning_bank bigint not null,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null,
        primary key (creditcard_id, customer_id)
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists address_owner 
       add constraint FK6qqrocb197cfxf5of7wc9cu5s 
       foreign key (owner_id) 
       references Customer;

    alter table if exists address_owner 
       add constraint FKtlveceg81q5bjp3h05wef8s8h 
       foreign key (address_id) 
       references Address;

    alter table if exists CreditCard 
       add constraint FKl2cxkcslw7r5abrhbtj0qjyqo 
       foreign key (owning_bank) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table address_owner (
        address_id bigint not null,
        owner_id bigint not null,
        primary key (address_id, owner_id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        id bigint generated by default as identity,
        owning_bank bigint not null,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null,
        primary key (creditcard_id, customer_id)
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists address_owner 
       add constraint FK6qqrocb197cfxf5of7wc9cu5s 
       foreign key (owner_id) 
       references Customer;

    alter table if exists address_owner 
       add constraint FKtlveceg81q5bjp3h05wef8s8h 
       foreign key (address_id) 
       references Address;

    alter table if exists CreditCard 
       add constraint FKl2cxkcslw7r5abrhbtj0qjyqo 
       foreign key (owning_bank) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table address_owner (
        address_id bigint not null,
        owner_id bigint not null,
        primary key (address_id, owner_id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        id bigint generated by default as identity,
        owning_bank bigint not null,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null,
        primary key (creditcard_id, customer_id)
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists address_owner 
       add constraint FK6qqrocb197cfxf5of7wc9cu5s 
       foreign key (owner_id) 
       references Customer;

    alter table if exists address_owner 
       add constraint FKtlveceg81q5bjp3h05wef8s8h 
       foreign key (address_id) 
       references Address;

    alter table if exists CreditCard 
       add constraint FKl2cxkcslw7r5abrhbtj0qjyqo 
       foreign key (owning_bank) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table address_owner (
        address_id bigint not null,
        owner_id bigint not null,
        primary key (address_id, owner_id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        id bigint generated by default as identity,
        owning_bank bigint not null,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null,
        primary key (creditcard_id, customer_id)
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists address_owner 
       add constraint FK6qqrocb197cfxf5of7wc9cu5s 
       foreign key (owner_id) 
       references Customer;

    alter table if exists address_owner 
       add constraint FKtlveceg81q5bjp3h05wef8s8h 
       foreign key (address_id) 
       references Address;

    alter table if exists CreditCard 
       add constraint FKl2cxkcslw7r5abrhbtj0qjyqo 
       foreign key (owning_bank) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table address_owner (
        address_id bigint not null,
        owner_id bigint not null,
        primary key (address_id, owner_id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        id bigint generated by default as identity,
        owning_bank bigint not null,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null,
        primary key (creditcard_id, customer_id)
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists address_owner 
       add constraint FK6qqrocb197cfxf5of7wc9cu5s 
       foreign key (owner_id) 
       references Customer;

    alter table if exists address_owner 
       add constraint FKtlveceg81q5bjp3h05wef8s8h 
       foreign key (address_id) 
       references Address;

    alter table if exists CreditCard 
       add constraint FKl2cxkcslw7r5abrhbtj0qjyqo 
       foreign key (owning_bank) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table address_owner (
        address_id bigint not null,
        owner_id bigint not null,
        primary key (address_id, owner_id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        id bigint generated by default as identity,
        owning_bank bigint not null,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null,
        primary key (creditcard_id, customer_id)
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists address_owner 
       add constraint FK6qqrocb197cfxf5of7wc9cu5s 
       foreign key (owner_id) 
       references Customer;

    alter table if exists address_owner 
       add constraint FKtlveceg81q5bjp3h05wef8s8h 
       foreign key (address_id) 
       references Address;

    alter table if exists CreditCard 
       add constraint FKl2cxkcslw7r5abrhbtj0qjyqo 
       foreign key (owning_bank) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;

    create table Address (
        number integer,
        id bigint generated by default as identity,
        street varchar(255),
        primary key (id)
    );

    create table address_owner (
        address_id bigint not null,
        owner_id bigint not null,
        primary key (address_id, owner_id)
    );

    create table Bank (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table CreditCard (
        balance integer,
        creditLimit integer,
        number integer,
        id bigint generated by default as identity,
        owning_bank bigint not null,
        pincode_id bigint,
        primary key (id)
    );

    create table Customer (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table customer_creditcard (
        creditcard_id bigint not null,
        customer_id bigint not null,
        primary key (creditcard_id, customer_id)
    );

    create table Pincode (
        count integer,
        id bigint generated by default as identity,
        code varchar(255),
        primary key (id)
    );

    create table Todo (
        id bigint generated by default as identity,
        description varchar(255),
        summary varchar(255),
        primary key (id)
    );

    alter table if exists address_owner 
       add constraint FK6qqrocb197cfxf5of7wc9cu5s 
       foreign key (owner_id) 
       references Customer;

    alter table if exists address_owner 
       add constraint FKtlveceg81q5bjp3h05wef8s8h 
       foreign key (address_id) 
       references Address;

    alter table if exists CreditCard 
       add constraint FKl2cxkcslw7r5abrhbtj0qjyqo 
       foreign key (owning_bank) 
       references Bank;

    alter table if exists CreditCard 
       add constraint FKfky0y471d7n8cebc1oe28idci 
       foreign key (pincode_id) 
       references Pincode;

    alter table if exists customer_creditcard 
       add constraint FKbqtt4y8vkl6a0hk4ud19wci0g 
       foreign key (creditcard_id) 
       references CreditCard;

    alter table if exists customer_creditcard 
       add constraint FKfjq2xyx1jh83r4h1t7f18kxj 
       foreign key (customer_id) 
       references Customer;
